-- Adds MFA (TOTP) support to auth-service.
--
-- Design decisions:
--
-- mfa_pending_secret vs mfa_secret (two-column approach):
--   Setup is a two-step flow:
--     1. POST /auth/mfa/setup   → generate secret, store as pending, return QR
--     2. POST /auth/mfa/enable  → verify TOTP code, move pending → active
--   If user abandons after step 1, the pending secret is cleaned up by
--   setupMfa() on next call. This prevents stale secrets accumulating.
--   Both columns store AES-256-GCM encrypted base32 secret.
--
-- mfa_secret encryption:
--   TOTP verification requires the original secret (to regenerate the code
--   and compare). BCrypt/Argon2 are one-way — they cannot be used here.
--   AES-256-GCM encryption with application-managed key (MFA_ENCRYPTION_KEY
--   env var) provides confidentiality: even if the DB is compromised, secrets
--   are unusable without the encryption key.
--
-- mfa_backup_codes — separate table, not array column:
--   Each backup code is used exactly once. A separate table with used_at
--   makes marking codes as used atomic and auditable. Array columns in
--   PostgreSQL are harder to index and update atomically per element.
--   code_hash is Argon2id — same algorithm as passwords for consistency.
--
-- tenant_settings — generic key-value would be premature optimization:
--   Using typed columns (mfa_required BOOLEAN) is simpler and type-safe.
--   If more settings are needed later, columns can be added via migration.

-- ── users: MFA columns ────────────────────────────────────────────────────

ALTER TABLE users
    ADD COLUMN mfa_enabled         BOOLEAN     NOT NULL DEFAULT FALSE,
    ADD COLUMN mfa_secret          VARCHAR(512),         -- AES-256-GCM encrypted base32
    ADD COLUMN mfa_pending_secret  VARCHAR(512),         -- temporary during setup
    ADD COLUMN mfa_enabled_at      TIMESTAMPTZ;

COMMENT ON COLUMN users.mfa_enabled
    IS 'Whether TOTP MFA is active for this user. '
       'False until POST /auth/mfa/enable is successfully called.';
COMMENT ON COLUMN users.mfa_secret
    IS 'AES-256-GCM encrypted base32 TOTP secret. '
       'NULL until MFA is enabled. Decrypted at verify time to generate TOTP.';
COMMENT ON COLUMN users.mfa_pending_secret
    IS 'Temporary secret generated by POST /auth/mfa/setup. '
       'Moved to mfa_secret on successful POST /auth/mfa/enable. '
       'Cleared if setup is restarted or abandoned.';

-- ── mfa_backup_codes ──────────────────────────────────────────────────────

CREATE TABLE mfa_backup_codes
(
    id        UUID        NOT NULL DEFAULT gen_random_uuid(),
    user_id   UUID        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    code_hash VARCHAR(100) NOT NULL,  -- Argon2id hash of the plain backup code
    used_at   TIMESTAMPTZ,            -- NULL = not yet used

    CONSTRAINT pk_mfa_backup_codes PRIMARY KEY (id)
);

CREATE INDEX idx_mfa_backup_codes_user
    ON mfa_backup_codes (user_id)
    WHERE used_at IS NULL;

COMMENT ON TABLE mfa_backup_codes
    IS 'Single-use backup codes for MFA recovery when authenticator app is unavailable. '
       'Generated when MFA is enabled. Each code is Argon2id-hashed.';

-- ── tenant_settings ───────────────────────────────────────────────────────

CREATE TABLE tenant_settings
(
    tenant_id    VARCHAR(255) NOT NULL,
    mfa_required BOOLEAN      NOT NULL DEFAULT FALSE,
    updated_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    CONSTRAINT pk_tenant_settings PRIMARY KEY (tenant_id)
);

COMMENT ON TABLE tenant_settings
    IS 'Per-tenant configuration. ADMIN-managed. '
       'mfa_required=true forces all users in the tenant to configure MFA '
       'before accessing the system.';
COMMENT ON COLUMN tenant_settings.mfa_required
    IS 'If true, users without MFA enabled are blocked at login with '
       'MFA_SETUP_REQUIRED error and redirected to /auth/mfa/setup.';