package com.incidentplatform.postmortem.domain;

/**
 * Lifecycle status of a {@link Postmortem}.
 *
 * <p>Used as {@code @Enumerated(EnumType.STRING)} so the database stores
 * the same string values as before — no Flyway migration required.
 */
public enum PostmortemStatus {

    /** Gemini API call in progress. */
    GENERATING,

    /** Draft generated by AI — awaiting engineer review. */
    DRAFT,

    /** AI generation failed — will be retried by scheduler. */
    FAILED,

    /** All retries exhausted — manual intervention required. */
    PERMANENTLY_FAILED,

    /** Engineer has reviewed and approved the postmortem. */
    REVIEWED
}