spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/incidentdb
    username: incident_app
    password: incident_secret

  jpa:
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092

logging:
  level:
    com.incidentplatform: TRACE
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

jwt:
  secret: local-development-secret-key-minimum-32-characters-long-not-for-production