package com.incidentplatform.postmortem.service;

import com.incidentplatform.postmortem.client.GeminiClient;
import com.incidentplatform.postmortem.client.GeminiException;
import com.incidentplatform.postmortem.domain.Postmortem;
import com.incidentplatform.postmortem.dto.PostmortemDto;
import com.incidentplatform.postmortem.dto.UpdatePostmortemRequest;
import com.incidentplatform.postmortem.repository.PostmortemRepository;
import com.incidentplatform.shared.audit.AuditEventPublisher;
import com.incidentplatform.shared.domain.Severity;
import com.incidentplatform.shared.exception.ResourceNotFoundException;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.Instant;
import java.util.List;
import java.util.Map;
import java.util.UUID;

@Service
public class PostmortemService {

    private static final Logger log =
            LoggerFactory.getLogger(PostmortemService.class);

    private static final String SERVICE_NAME = "postmortem-service";

    private final PostmortemRepository postmortemRepository;
    private final GeminiClient geminiClient;
    private final AuditEventPublisher auditEventPublisher;
    private final PostmortemPromptBuilder promptBuilder;

    public PostmortemService(PostmortemRepository postmortemRepository,
                             GeminiClient geminiClient,
                             AuditEventPublisher auditEventPublisher,
                             PostmortemPromptBuilder promptBuilder) {
        this.postmortemRepository = postmortemRepository;
        this.geminiClient = geminiClient;
        this.auditEventPublisher = auditEventPublisher;
        this.promptBuilder = promptBuilder;
    }

    @Transactional
    public void generatePostmortem(UUID incidentId,
                                   String tenantId,
                                   String incidentTitle,
                                   Severity incidentSeverity,
                                   Instant incidentOpenedAt,
                                   Instant incidentResolvedAt,
                                   int durationMinutes) {

        if (postmortemRepository.existsByIncidentId(incidentId)) {
            log.debug("Postmortem already exists for incidentId={}, skipping",
                    incidentId);
            return;
        }

        final Postmortem postmortem = Postmortem.createGenerating(
                incidentId, tenantId, incidentTitle, incidentSeverity.name(),
                incidentOpenedAt, incidentResolvedAt, durationMinutes);
        postmortemRepository.save(postmortem);

        log.info("Generating postmortem: incidentId={}, tenant={}, " +
                        "severity={}, durationMinutes={}",
                incidentId, tenantId, incidentSeverity, durationMinutes);

        try {
            final String prompt = promptBuilder.build(
                    incidentTitle, incidentSeverity.name(),
                    durationMinutes, incidentOpenedAt, incidentResolvedAt);

            final String content = geminiClient.generate(prompt);

            postmortem.markDraft(content, prompt);
            postmortemRepository.save(postmortem);

            log.info("Postmortem generated successfully: incidentId={}, " +
                            "tenant={}, contentLength={}",
                    incidentId, tenantId, content.length());

            auditEventPublisher.publishSystem(
                    incidentId, tenantId,
                    "POSTMORTEM_GENERATED", SERVICE_NAME,
                    String.format("Postmortem draft generated by Gemini AI. " +
                            "Content length: %d characters.", content.length()),
                    Map.of("contentLength", content.length(),
                            "status", "DRAFT",
                            "durationMinutes", durationMinutes)
            );

        } catch (GeminiException e) {
            postmortem.markFailed(e.getMessage());
            postmortemRepository.save(postmortem);

            log.error("Failed to generate postmortem: incidentId={}, " +
                            "tenant={}, error={}", incidentId, tenantId,
                    e.getMessage());

            auditEventPublisher.publishSystem(
                    incidentId, tenantId,
                    "POSTMORTEM_FAILED", SERVICE_NAME,
                    String.format("Postmortem generation failed: %s",
                            e.getMessage()),
                    Map.of("error", e.getMessage(),
                            "status", "FAILED")
            );
        }
    }

    @Transactional(readOnly = true)
    public List<PostmortemDto> getPostmortems(String tenantId) {
        return postmortemRepository
                .findByTenantIdOrderByCreatedAtDesc(tenantId)
                .stream()
                .map(PostmortemDto::from)
                .toList();
    }

    @Transactional(readOnly = true)
    public PostmortemDto getByIncidentId(UUID incidentId, String tenantId) {
        return postmortemRepository
                .findByIncidentIdAndTenantId(incidentId, tenantId)
                .map(PostmortemDto::from)
                .orElseThrow(() -> new ResourceNotFoundException(
                        "Postmortem", incidentId));
    }

    @Transactional
    public PostmortemDto updateContent(UUID incidentId,
                                       String tenantId,
                                       UpdatePostmortemRequest request) {
        final Postmortem postmortem = postmortemRepository
                .findByIncidentIdAndTenantId(incidentId, tenantId)
                .orElseThrow(() -> new ResourceNotFoundException(
                        "Postmortem", incidentId));

        postmortem.updateContent(request.content());
        postmortemRepository.save(postmortem);

        log.info("Postmortem updated: incidentId={}, tenant={}",
                incidentId, tenantId);

        auditEventPublisher.publishSystem(
                incidentId, tenantId,
                "POSTMORTEM_UPDATED", SERVICE_NAME,
                "Postmortem content updated by engineer.",
                Map.of("status", postmortem.getStatus())
        );

        return PostmortemDto.from(postmortem);
    }
}