package com.incidentplatform.postmortem.service;

import com.incidentplatform.postmortem.domain.Postmortem;
import com.incidentplatform.postmortem.domain.PostmortemStatus;
import com.incidentplatform.postmortem.repository.PostmortemRepository;
import com.incidentplatform.shared.audit.AuditEventPublisher;
import com.incidentplatform.shared.audit.AuditEventTypes;
import com.incidentplatform.shared.domain.Severity;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.Instant;
import java.util.Map;
import java.util.UUID;

/**
 * Isolates the three short, independent database transactions involved in
 * postmortem generation from the long-running Gemini API call that sits
 * between them.
 *
 * <h2>Why this is a separate class, not three {@code @Transactional} methods
 * on {@link PostmortemService}</h2>
 * Spring's {@code @Transactional} is implemented via a proxy — calling
 * {@code this.someTransactionalMethod()} from within the same class bypasses
 * the proxy entirely, silently ignoring the annotation (the classic
 * self-invocation pitfall). Putting these three methods in a separate,
 * injected {@code @Service} guarantees each call goes through Spring's proxy
 * and actually opens/commits its own short transaction.
 *
 * <h2>Why this matters</h2>
 * {@code PostmortemService.generatePostmortem()} previously wrapped the
 * entire flow — including {@code geminiClient.generate(prompt)}, an external
 * HTTP call typically taking seconds — in a single {@code @Transactional}
 * method. A database connection (from a typically 10-connection HikariCP
 * pool) was held for the full duration of that external call. Under
 * concurrent load (e.g. a mass outage resolving many incidents at once),
 * this could exhaust the connection pool and stall unrelated REST requests
 * being served by the same service.
 *
 * <p>Each method here is a short, independent transaction containing only
 * database writes — the connection is acquired and released in milliseconds.
 * The Gemini call in {@link PostmortemService#generatePostmortem} now happens
 * entirely outside any open transaction.
 */
@Service
public class PostmortemPersistenceService {

    private static final String SERVICE_NAME = "postmortem-service";

    private final PostmortemRepository postmortemRepository;
    private final AuditEventPublisher auditEventPublisher;

    public PostmortemPersistenceService(PostmortemRepository postmortemRepository,
                                        AuditEventPublisher auditEventPublisher) {
        this.postmortemRepository = postmortemRepository;
        this.auditEventPublisher = auditEventPublisher;
    }

    /**
     * Creates and persists the initial {@code GENERATING} record.
     * Short transaction — INSERT only, no external calls.
     */
    @Transactional
    public UUID createGeneratingRecord(UUID incidentId,
                                       String tenantId,
                                       String incidentTitle,
                                       Severity incidentSeverity,
                                       Instant incidentOpenedAt,
                                       Instant incidentResolvedAt,
                                       int durationMinutes) {
        final Postmortem postmortem = Postmortem.createGenerating(
                incidentId, tenantId, incidentTitle, incidentSeverity.name(),
                incidentOpenedAt, incidentResolvedAt, durationMinutes);
        postmortemRepository.save(postmortem);
        return postmortem.getId();
    }

    /**
     * Marks the postmortem as {@code DRAFT} with Gemini-generated content
     * and publishes the success audit event. Short transaction — UPDATE only,
     * called after the Gemini call has already completed.
     */
    @Transactional
    public void markDraftAndPublish(UUID postmortemId,
                                    UUID incidentId,
                                    String tenantId,
                                    String content,
                                    String prompt,
                                    int durationMinutes) {
        final Postmortem postmortem = postmortemRepository.getReferenceById(postmortemId);
        postmortem.markDraft(content, prompt);
        postmortemRepository.save(postmortem);

        auditEventPublisher.publishSystem(
                incidentId, tenantId,
                AuditEventTypes.POSTMORTEM_GENERATED, SERVICE_NAME,
                String.format("Postmortem draft generated by Gemini AI. " +
                        "Content length: %d characters.", content.length()),
                Map.of("contentLength", content.length(),
                        "status", PostmortemStatus.DRAFT.name(),
                        "durationMinutes", durationMinutes)
        );
    }

    /**
     * Marks the postmortem as {@code FAILED} and publishes the failure audit
     * event. Short transaction — UPDATE only, called after the Gemini call
     * has already failed.
     */
    @Transactional
    public void markFailedAndPublish(UUID postmortemId,
                                     UUID incidentId,
                                     String tenantId,
                                     String errorMessage) {
        final Postmortem postmortem = postmortemRepository.getReferenceById(postmortemId);
        postmortem.markFailed(errorMessage);
        postmortemRepository.save(postmortem);

        auditEventPublisher.publishSystem(
                incidentId, tenantId,
                AuditEventTypes.POSTMORTEM_FAILED, SERVICE_NAME,
                String.format("Postmortem generation failed: %s", errorMessage),
                Map.of("error", errorMessage,
                        "status", PostmortemStatus.FAILED.name())
        );
    }
}