apiVersion: v1
kind: Service
metadata:
  name: notification-service
  labels:
    app: notification-service
    app.kubernetes.io/part-of: incident-platform
spec:
  selector:
    app: notification-service
  ports:
    - name: http
      port: 8083
      targetPort: 8083
    - name: management
      port: 8093
      targetPort: 8093
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: notification-service-hpa
  labels:
    app.kubernetes.io/part-of: incident-platform
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: notification-service
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80